#!/bin/sh

###############################################################################
# put environment variables here
###############################################################################

# set svn editor to vim
export EDITOR=vim
export SVN_EDITOR="$EDITOR"

# add user bin and software bin to PATH
export PATH="$HOME/bin:$HOME/software/bin:$PATH"

# GO related env vars
export GO_HOME="$HOME/software/sdk/go/bin"
export PATH="$GO_HOME:$PATH"
[ -x "$(command -v go)" ] && export PATH="$(go env GOPATH)/bin:$PATH"


