#!/bin/zsh

# general functions

fs() {
    fd --no-ignore-vcs ${@} | tree --fromfile
}

# git functions

gsync() {
    branch_name=$(git rev-parse --abbrev-ref HEAD)
    git branch | grep -E "^\*?\s+(main|master)$" | xargs git checkout
    git fetch && git pull
    git checkout $branch_name
    git branch | grep -E "^\*?\s+(main|master)$" | xargs git rebase
}
