;; extends
;; CSS Tree-sitter Overrides for Converged Ergonomic Solarized Scheme

((tag_name) @tag (#set! priority 130))
((universal_selector) @tag (#set! priority 130))
((class_name) @type.css (#set! priority 130))
((id_name) @type.css (#set! priority 130))
((id_selector) @type.css (#set! priority 130))
((pseudo_class_selector (class_name) @attribute) (#set! priority 130))
((pseudo_element_selector "::" (tag_name) @attribute) (#set! priority 130))
((nesting_selector) @operator (#set! priority 130))
((attribute_name) @tag.attribute (#set! priority 130))
(attribute_selector ["[" "]"] @punctuation.delimiter (#set! priority 130))
(attribute_selector ["=" "^=" "$=" "*=" "~=" "|="] @operator (#set! priority 130))
((property_name) @property.css (#set! priority 130))
((plain_value) @variable.css (#set! priority 130))
((property_name) @variable.css (#lua-match? @variable.css "^[-][-]") (#set! priority 135))
((plain_value) @variable.css (#lua-match? @variable.css "^[-][-]") (#set! priority 135))
((function_name) @function.call.css (#set! priority 130))
((color_value) @string.special.css (#set! priority 130))
((unit) @type.builtin.css (#set! priority 130))
((string_value) @string (#set! priority 130))
((important) @keyword.modifier.css (#set! priority 130))
("@container" @keyword.directive (#set! priority 130))
((container_name) @variable.css (#set! priority 130))
((feature_name) @variable.css (#set! priority 130))
