#!/bin/bash

set -o errexit   # abort on nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes

UPPER="A-Z"
LOWER="a-z"
NUMBERS="0-9"
SYMBOLS='!@#$%^&*()_+=[]{}|:,.<>?-'

LENGTH="16"
CHARACTER_SET=""

usage() {
    echo "usage: $(basename "$0") [-u -l -n -s] <length>"
}

while getopts ":ulnsht" opt; do
  case ${opt} in
    u )
      CHARACTER_SET="$CHARACTER_SET$UPPER"
      ;;
    l )
      CHARACTER_SET="$CHARACTER_SET$LOWER"
      ;;
    n )
      CHARACTER_SET="$CHARACTER_SET$NUMBERS"
      ;;
    s )
      CHARACTER_SET="$CHARACTER_SET$SYMBOLS"
      ;;
    h )
      usage
      exit 0
      ;;
    t )
      set -o xtrace # toggle trace
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      usage
      exit 1
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))

if [ "${1:-}" != "" ]; then
  LENGTH="$1"
fi

if [ "$LENGTH" = "" ]; then
  echo "a length must be provided"
  usage
  exit 1
fi

INTEGER='^[0-9]+$'
if ! [[ $LENGTH =~ $INTEGER ]] ; then
   echo "error: $LENGTH is not a number"
   exit 1
fi

if [ "$CHARACTER_SET" = "" ]; then
  CHARACTER_SET="$UPPER$LOWER$NUMBERS$SYMBOLS"
fi

# Disable pipefail because head -c closes the pipe early, causing tr to receive SIGPIPE (Broken pipe)
set +o pipefail
< /dev/urandom LC_ALL=C tr -dc "$CHARACTER_SET" 2>/dev/null | head -c "$LENGTH"
set -o pipefail
echo

