#!/bin/bash

set -o errexit   # abort on nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes

SDK_DIR="$HOME/software/sdk"
VERSION_REGEX='^go[0-9]+\.[0-9]+\.[0-9]+$'

GO_VERSION=""

usage() {
    echo "usage: $(basename "$0") [-v]"
}

listVersions() {
  git -c 'versionsort.suffix=-' ls-remote \
    --exit-code \
    --refs --sort='version:refname' \
    --tags https://go.googlesource.com/go 'go*.*.*' \
    | cut --delimiter='/' --fields=3
}

while getopts ":v:lht" opt; do
  case ${opt} in
    v )
      GO_VERSION="$OPTARG"
      ;;
    l )
      listVersions 
      exit 0
      ;;
    h )
      usage
      exit 0
      ;;
    t )
      set -o xtrace # toggle trace
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      usage
      exit 1
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))

if ! [[ "$GO_VERSION" =~ $VERSION_REGEX ]]; then
    echo "malformed version. '$GO_VERSION' is not a valid go version" 1>&2
    exit 1
fi

mkdir -p "$SDK_DIR"

if [ -d "$SDK_DIR/$GO_VERSION" ]; then
    echo "$GO_VERSION is already installed"
    exit 0
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="amd64"
case "$(uname -m)" in
    x86_64) ARCH="amd64" ;;
    aarch64|arm64) ARCH="arm64" ;;
esac

TARBALL="$TMP_DIR/$GO_VERSION.$OS-$ARCH.tar.gz"
DOWNLOAD_URL="https://go.dev/dl/$GO_VERSION.$OS-$ARCH.tar.gz"

if command -v curl &>/dev/null; then
    curl -fsSL "$DOWNLOAD_URL" -o "$TARBALL"
elif command -v wget &>/dev/null; then
    wget "$DOWNLOAD_URL" -O "$TARBALL"
else
    echo "error: neither curl nor wget found" >&2
    exit 1
fi

tar -xzf "$TARBALL" -C "$TMP_DIR"
mv "$TMP_DIR/go" "$SDK_DIR/$GO_VERSION"

