#!/bin/bash

SDK_DIR="$HOME/software/sdk"
VERSION_REGEX='^[0-9]+\.[0-9]+\.[0-9]+$'

GO_VERSION=""

usage() {
    echo "usage: $(basename "$0") [-v]"
}

while getopts ":v:h" opt; do
  case ${opt} in
    v )
      GO_VERSION="$OPTARG"
      ;;
    h )
      usage
      exit 0
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      usage
      exit 1
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))

if ! [[ "$GO_VERSION" =~ $VERSION_REGEX ]]; then
    echo "malformed version. '$GO_VERSION' is not  a semantic version number" 1>&2
    exit 1
fi

if [ -d "$SDK_DIR/go$GO_VERSION" ]; then
    echo "go$GO_VERSION is already installed"
    exit 0
fi

wget "https://go.dev/dl/go$GO_VERSION.linux-amd64.tar.gz" -P /tmp
tar -xzvf "/tmp/go$GO_VERSION.linux-amd64.tar.gz" -C /tmp
mv /tmp/go "$SDK_DIR/go$GO_VERSION"
