#!/bin/bash

SDK_DIR="$HOME/software/sdk"
VERSION_REGEX='^go[0-9]+\.[0-9]+\.[0-9]+$'

GO_VERSION=""

usage() {
    echo "usage: $(basename "$0") [-v]"
}

listVersions() {
  git -c 'versionsort.suffix=-' ls-remote \
    --exit-code \
    --refs --sort='version:refname' \
    --tags https://go.googlesource.com/go 'go*.*.*' \
    | cut --delimiter='/' --fields=3
}

while getopts ":v:hl" opt; do
  case ${opt} in
    v )
      GO_VERSION="$OPTARG"
      ;;
    h )
      usage
      exit 0
      ;;
    l )
      listVersions 
      exit 0
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      usage
      exit 1
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))

if ! [[ "$GO_VERSION" =~ $VERSION_REGEX ]]; then
    echo "malformed version. '$GO_VERSION' is not a valid go version" 1>&2
    exit 1
fi

if [ -d "$SDK_DIR/$GO_VERSION" ]; then
    echo "$GO_VERSION is already installed"
    exit 0
fi

wget "https://go.dev/dl/$GO_VERSION.linux-amd64.tar.gz" -P /tmp
tar -xzvf "/tmp/$GO_VERSION.linux-amd64.tar.gz" -C /tmp
mv /tmp/go "$SDK_DIR/$GO_VERSION"

