#!/bin/bash

set -o errexit   # abort on nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes

VERSION_REGEX='^[0-9]+\.[0-9]+\.[0-9]+$'

TF_VERSION=""

usage() {
    echo "usage: $(basename "$0") [-v]"
}

while getopts ":v:ht" opt; do
  case ${opt} in
    v )
      TF_VERSION="$OPTARG"
      ;;
    h )
      usage
      exit 0
      ;;
    t )
      set -o xtrace # toggle trace
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      usage
      exit 1
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))

if ! [[ "$TF_VERSION" =~ $VERSION_REGEX ]]; then
    echo "malformed version. '$TF_VERSION' is not  a semantic version number" 1>&2
    exit 1
fi

BIN_DIR="$HOME/bin"
mkdir -p "$BIN_DIR"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="amd64"
case "$(uname -m)" in
    x86_64) ARCH="amd64" ;;
    aarch64|arm64) ARCH="arm64" ;;
esac

ZIP_FILE="$TMP_DIR/terraform_${TF_VERSION}_${OS}_${ARCH}.zip"
DOWNLOAD_URL="https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_${OS}_${ARCH}.zip"

if command -v curl &>/dev/null; then
    curl -fsSL "$DOWNLOAD_URL" -o "$ZIP_FILE"
elif command -v wget &>/dev/null; then
    wget "$DOWNLOAD_URL" -O "$ZIP_FILE"
else
    echo "error: neither curl nor wget found" >&2
    exit 1
fi

unzip -o -d "$TMP_DIR" "$ZIP_FILE"
chmod +x "$TMP_DIR/terraform"
mv "$TMP_DIR/terraform" "$BIN_DIR/terraform"

