#!/bin/bash

set -o errexit   # abort on nonzero exitstatus. Same as 'set -e'
set -o nounset   # abort on unbound variable. Same as 'set -u'
set -o pipefail  # don't hide errors within pipes

# Uncomment below line when debugging to get trace output
# set -o xtrace    # print trace

MAX_ATTEMPTS="10"
SLEEP_SECONDS=30

usage() {
    echo "usage: $(basename "$0") -n MAX_ATTEMPT cmd" 
}

while getopts ":n:s:h" opt; do
  case ${opt} in
    n )
      MAX_ATTEMPTS=$OPTARG
      ;;
    s )
      SLEEP_SECONDS=$OPTARG
      ;;
    h )
      usage
      exit 0
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      usage
      exit 1
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))

for ((i=0;i<MAX_ATTEMPTS;i++)); do
    echo "attempting cmd: $*"
    set +o errexit
    "${@}"
    exit_code="$?"
    set -o errexit
    if [ $exit_code -eq 0 ]; then
        echo "cmd succeeded"
        exit 0
    fi
    echo "cmd failed with status $exit_code, retrying in $SLEEP_SECONDS seconds"
    sleep "$SLEEP_SECONDS"
done
echo "max retries limit of $MAX_ATTEMPTS has been reached"
exit 1
