#!/bin/bash

set -o errexit   # abort on nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes

MAX_ATTEMPTS="10"
SLEEP_SECONDS=30

usage() {
    echo "usage: $(basename "$0") -n MAX_ATTEMPT cmd" 
}

while getopts ":n:s:ht" opt; do
  case ${opt} in
    n )
      MAX_ATTEMPTS=$OPTARG
      ;;
    s )
      SLEEP_SECONDS=$OPTARG
      ;;
    h )
      usage
      exit 0
      ;;
    t )
      set -o xtrace # toggle trace
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      usage
      exit 1
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))

if [ "$#" -eq 0 ]; then
    echo "error: no command specified" 1>&2
    usage
    exit 1
fi

for ((i=1; i<=MAX_ATTEMPTS; i++)); do
    echo "attempting (attempt $i/$MAX_ATTEMPTS) cmd: $*"
    if "$@"; then
        echo "cmd succeeded"
        exit 0
    else
        exit_code="$?"
        echo "cmd failed with status $exit_code"
        if [ "$i" -lt "$MAX_ATTEMPTS" ]; then
            echo "retrying in $SLEEP_SECONDS seconds..."
            sleep "$SLEEP_SECONDS"
        fi
    fi
done

echo "max retries limit of $MAX_ATTEMPTS has been reached" 1>&2
exit 1

