#!/bin/bash

set -o errexit   # abort on nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes

SDK_DIR="$HOME/software/sdk"
VERSION_REGEX="^go[0-9]+\.[0-9]+\.[0-9]+$"

GO_VERSION=""

usage() {
    echo "usage: $(basename "$0") [-v <version>] [-l] [-t]"
}

list_versions() {
  if [ -d "$SDK_DIR" ]; then
    find "$SDK_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | grep -v '^go$' | sort -V || true
  fi
}

while getopts ":v:lht" opt; do
  case ${opt} in
    v )
      GO_VERSION="$OPTARG"
      ;;
    l )
      list_versions
      exit 0
      ;;
    h )
      usage
      exit 0
      ;;
    t )
      set -o xtrace # toggle trace
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      usage
      exit 1
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))

if ! [[ "$GO_VERSION" =~ $VERSION_REGEX ]]; then
    echo "malformed version. '$GO_VERSION' is not a valid go version" 1>&2
    exit 1
fi

if ! [ -d "$SDK_DIR/$GO_VERSION" ]; then
    echo "$GO_VERSION is not installed" 1>&2
    exit 1
fi

ln -sfn "$SDK_DIR/$GO_VERSION" "$SDK_DIR/go"

